name: Bug Report
description: Submit a bug to the devs
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug in details...
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior
      placeholder: "1. Go to ''...''\n2. Click on ''....''\n3. Scroll down to ''....''\n4. See error\n"
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: false
  - type: input
    id: version
    attributes:
      label: Game Version
      description: What version of the game are you running?
      placeholder: 2.4.0 (24015)
    validations:
        required: true
  - type: textarea
    id: attachments
    attributes:
      label: Attachments
      description: Upload attachments such as screenshots, debug log etc.
      placeholder: Upload attachments by clicking or dragging files to the bar right below this text.
    validations:
        required: false
